### ISSUE TITLE
Argument `userId` is missing.

### ISSUE THREAD

**Issue by WNortier** [kleydon/prisma-session-store#127]
I'm trying to implement PrismaSessionStore in my nestjs app, but it keeps requiring a userId. 
This is the error I'm running into: 
`  
  540 case 4:
  541     _a.sent();
  542     return [3 /*break*/, 7];
→ 543 case 5: return [4 /*yield*/, this.prisma[this.sessionModelName].create({
        data: {
          sid: "VTCF2Q4z3gfaPMXyzKXElEW6uiVdqKKn",
          expiresAt: new Date("2024-06-03T07:58:15.925Z"),
          data: "{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"isAuth\":true,\"userId\":\"1\"}",
          id: "VTCF2Q4z3gfaPMXyzKXElEW6uiVdqKKn",
      +   userId: String
        }
      })
Argument `userId` is missing.
`

Any thoughts on this?

**Comment by kleydon** [comment]
Hi @WNortier,
Unfortunately I don't have any experience with  nestjs.
Anyone else out there run into this sort of thing?

**Comment by WNortier** [comment]
Something was wrong with my implementation, when I followed the TypeScript examples on their documentation it worked.

**Comment by kleydon** [comment]
@WNortier Glad to hear it!
