### ISSUE TITLE
Session data is too long for default String type when using mysql

### ISSUE THREAD

**Issue by olivierwilkinson** [kleydon/prisma-session-store#21]
Hi, love the project! Was very happy to discover I could keep my session store within the prisma ecosystem. I wanted to flag a problem I had getting set up with mysql:

I was finding the following error when creating a session:
```
Invalid `prisma.session.update()` invocation:

  The provided value for the column is too long for the column's type. Column: data
```

The prisma String type defaults to a VarChar of length 191 which is what I suspect the problem was. If I manually update the `Session.data` column to LongText then the problem goes away:
```
ALTER TABLE Session MODIFY data LONGTEXT;
```

Prisma are currently working on adding schema annotations that can be used to control which underlying type your schema will map to: https://www.prisma.io/docs/concepts/components/preview-features/native-types/. However using prisma migrate with the new annotations is not currently supported, they are working on it though: https://github.com/prisma/prisma-engines/issues/72.

Anyways I thought it would be good to bring this up in case you wanted to add some notes to your README (or I could make a PR for my first open-source contribution 🤭). Even just having this issue to refer to might be enough to help mysql users on their way, up to you 😄. If you have any suggestions for the type to use for the data column that would be great, or if there is a way of changing the schema so that no manual intervention is needed that would be amazing (but it looks like it's probably not worth it long-term 🤷‍♂️ ).

Again, thanks for the project, after the above it's working like a charm. 👍

**Comment by wSedlacek** [comment]
If you could make a PR under `Setup > MYSQL` in the `README.md` that would be great.

**Comment by olivierwilkinson** [comment]
> If you could make a PR under `Setup > MYSQL` in the `README.md` that would be great.

Brilliant, I'll get on that tonight 👍

**Comment by kleydon** [comment]
Hi Oliver,

Glad your finding this project beneficial.

I'm on the road at the moment, but will tend to this when I can.

-K

**Comment by kleydon** [comment]
Woops! Just saw wSedlacek's reply.
-K
