### ISSUE TITLE
Relation to User

### ISSUE THREAD

**Issue by HartS** [kleydon/prisma-session-store#39]
The documentation states that the Session model should look like:

```
model Session {
  id        String   @id
  sid       String   @unique
  data      String
  expiresAt   DateTime
}
```

I'd expect to see a one-to-many relationship with users (after all, sessions are primarily used by users)

Something like:
```
  user      User     @relation(fields: [userId], references: [id])
  userId    Int
```

and in the User model:
```
  Session        Session[]
```

I'm going to go ahead and try this, but documentation would help with onboarding here.

**Comment by wSedlacek** [comment]
Typically with `express-session` you would not store additional fields on your Session model but instead use the `data` field.

### Example
```ts
req.session.userID = "some-id";
```

Then in a future request you can retrieve that data.
```ts
prisma.user.findOne({ id: req.session.userID });
```

This is the pattern used by libraries like [passport](https://www.npmjs.com/package/passport).
[Source Code](https://github.com/jaredhanson/passport/blob/9b9dbaa3eb3fc3b561812d95793e1ff6a355c3b8/lib/sessionmanager.js#L25)

Ideally you should not be making any calls directly to `prisma.session` anywhere in your code and letting `prisma-session-store` do all those calls for you.

**Comment by HartS** [comment]
Ended up implementing this with the above guidance, thank you!
