### ISSUE TITLE
discussion about working example for express session

### ISSUE THREAD

**Issue by ghinks** [kleydon/prisma-session-store#6]
Hello, thank you for your contribution to the express session project. As part of my due diligence on the triage team I just wanted to confirm that the module did in fact work.

I setup a postgres DB in the manner described and executed the prisma introspect command. Alas when I tried a basic test it fail. I am going to post a [link to my example](https://github.com/ghinks/express-session-pr-760-diligence) so you can explain what I am doing incorrectly.

**Comment by kleydon** [comment]
Hi ghinks,

Of Prisma's 3 parts - Client (for composing type-safe queries), Studio (an admin UI), and Migrate (introspection, migrations and initial setup), only Client is considered to be at a non-experimental stage. So it is possible that you are doing everything correctly, and that Migrate is misbehaving.

I've only ever used Prisma in the other direction (creating a schema and updating a db from it), so I might not have any deep insight - but I'll take a look.
