### ISSUE TITLE
Randomly unable to log in

### ISSUE THREAD

**Issue by YaakovR** [kleydon/prisma-session-store#71]
At random times, I am unable to log in until manually deleting the user's last session record from the database. 
While I do not know what is causing this issue, I'll do my best to provide context so hopefully someone can advise.

This is the error I'm getting:
![prisma-session-store error](https://user-images.githubusercontent.com/18146209/148292256-3e94a6a1-c5cc-44f2-88c8-6ecd757cb61b.png)

initializeSession.js
```
const express = require('express');
const session = require('express-session');
const { PrismaSessionStore } = require('@quixo3/prisma-session-store');
const prisma = require('../prisma/client');

const app = express();

module.exports = app.use(
  session({
    cookie: {
      maxAge: 1440 * 60 * 1000,
    },
    resave: false,
    saveUninitialized: false,
    secret: 'a very secretive secret',
    store: new PrismaSessionStore(prisma, {
        checkPeriod: 60 * 60 * 1000,
        dbRecordIdIsSessionId: false,
      },
    ),
  }),
);
```

Prisma schema:
```
model Session {
  id        String   @id
  sid       String   @unique
  data      String
  expiresAt DateTime @map("expires_at")

  @@map("sessions")
}
```

The data column content what is seemingly causing the issue.
This is the content in the data column when logging in for the first time:
`{"cookie":{"originalMaxAge":86400000,"expires":"2022-01-06T21:15:15.744Z","httpOnly":true,"path":"/"},"passport":{"user":1}}`

Once the issue occurs, the content in the data column looks like this:
`{"cookie":{"originalMaxAge":86400000,"expires":"2022-01-06T21:17:41.768Z","httpOnly":true,"path":"/"},"passport":{},"OIDC: 2fa02a06-56bd-4978-9a7d-60869b77c0c3":{"content":[{"state":"JtIlEc4fsMmNXpSNlEN5k5zO1Uiy5Jy-","nonce":"X1EcNC00MOz3HqVZYsDliNoc-oR3vVyD","timeStamp":1641417461767}]}}`

Once in this state, the data continues to add another context item on each subsequent login attempt until it exceeds the max size allowed by the database :
`{"cookie":{"originalMaxAge":86400000,"expires":"2022-01-06T21:19:06.824Z","httpOnly":true,"path":"/"},"passport":{},"OIDC: 2fa02a06-56bd-4978-9a7d-60869b77c0c3":{"content":[{"state":"JtIlEc4fsMmNXpSNlEN5k5zO1Uiy5Jy-","nonce":"X1EcNC00MOz3HqVZYsDliNoc-oR3vVyD","timeStamp":1641417461767},{"state":"myq0iWOcczpLgk4paRDjHCrASzBjO1zS","nonce":"SBoY5gffW5bCW0Iz_V8DBOGkz4harFk_","timeStamp":1641417531785},{"state":"IOp48R8-k2ZkCRM7eD5cMRzQAatM6y_7","nonce":"4E8HbnFUR0jqEWAcXOSr2ruicnteU13o","timeStamp":1641417540355},{"state":"vkTKQcRQGQTtCVTY_nqI71VthTxihDS9","nonce":"0P7dfnRTYGxpv5ockqJO9oCv-OxCykxu","timeStamp":1641417542968},{"state":"paunuwJ2vSQhMbzlT0xt7Xv0a2ezBbrB","nonce":"TqFfoXI1g64_ouwkPDnlZaWxeazCSLHA","timeStamp":1641417544087},{"state":"YxUxCoSLzVTChdh3pEhD1QLCl_sFJyxS","nonce":"s4MXNgX_dkuIXfYUzjhLHnLP3KAcEuRU","timeStamp":1641417545192},{"state":"V-5ENeBUzDNp8V-raypK-qf8YtzmprWt","nonce":"l1Nac8uZYQgD1wMCtmR-B1LMpuqZn_8U","timeStamp":1641417546360}]}}`

Any help will be appreciated!

**Comment by kleydon** [comment]
Hi @YaakovR,

Strange; not sure what is going on.

A couple of random ideas:
* Perhaps the key "OIDC: 2fa02a06-56bd-4978-9a7d-60869b77c0c3" is meant to be a key / value pair and formatting is getting garbled somewhere along the line?
* Perhaps somewhere along the line a conversion from string to object (or back) isn't happening as expected? Maybe due to an implicit conversion, or some escaped character issue?
* Is the behavior any different if the `resave` and `saveUninitialized` options are set to `true`?

Hope this suggests something to try; curious what's going on here...

**Comment by YaakovR** [comment]
This is the issue I was experiencing https://github.com/AzureAD/passport-azure-ad/issues/515.

**Comment by kleydon** [comment]
@YaakovR great to hear you found a fix - and thanks for posting it. 
(Bugs with intermittent behavior can be a _lot_ harder to track down!)
